- hosts: prometheus
  become: true
  tasks:
    - name: Creating the Process user for Prometheus
      user: 
        name: "prometheus"
        shell: "/bin/false"
        create_home: "no"

    - name: Creating the Process user for Node Exporter
      user: 
        name: "node_exporter"
        shell: "/bin/false"
        create_home: "no"

    - name: Creating the Prometheus Configuration Directory in etc
      file:
        path: "/etc/prometheus"
        owner: "prometheus"
        group: "prometheus"
        state: "directory"
    
    - name: Creating the Prometheus Configuration Directory in lib
      file:
        path: "/var/lib/prometheus"
        owner: "prometheus"
        group: "prometheus"
        state: "directory"
    
    - name: Downloading Prometheus Installion
      unarchive:
        src: "https://github.com/prometheus/prometheus/releases/download/v2.0.0/prometheus-2.0.0.linux-amd64.tar.gz"
        dest: "/tmp"
        remote_src: "yes"

    - name: Copy file prometheus with owner and permissions to bin folder
      copy:
        src: "/tmp/prometheus-2.0.0.linux-amd64/prometheus"
        dest: "/usr/local/bin/"
        owner: "prometheus"
        group: "prometheus"
        remote_src: "yes"
        mode: "0755"

    - name: Copy folder promtool with owner and permissions to bin folder
      copy:
        src: "/tmp/prometheus-2.0.0.linux-amd64/promtool"
        dest: "/usr/local/bin/"
        owner: "prometheus"
        group: "prometheus"
        remote_src: "yes"
        mode: "0755"
          
    - name: Copy folder consoles  with owner and permissions to etc folder
      copy:
        src: "/tmp/prometheus-2.0.0.linux-amd64/consoles"
        dest: "/etc/prometheus"
        owner: "prometheus"
        group: "prometheus"
        remote_src: "yes"
    
    - name: Copy folder console_libraries with owner and permissions to etc folder
      copy:
        src: "/tmp/prometheus-2.0.0.linux-amd64/console_libraries"
        dest: "/etc/prometheus"
        owner: "prometheus"
        group: "prometheus"
        remote_src: "yes"

    - name: Delete prometheus tar.gz folder from tmp folder
      file:
        path: "/tmp/prometheus-2.0.0.linux-amd64.tar.gz"
        state: "absent"

    - name: Delete prometheus folder from tmp folder
      file:
        path: "/tmp/prometheus-2.0.0.linux-amd64"
        state: "absent"

    - name: Copy file prometheus.yml to etc folder
      copy:
        src: "/root/Prometheus/config/prometheus.yml"
        dest: "/etc/prometheus/prometheus.yml"
        owner: "prometheus"
        group: "prometheus"

    - name: Copy file Prometheus service
      copy:
        src: "/root/Prometheus/config/prometheus.service"
        dest: "/etc/systemd/system/prometheus.service"
        owner: "prometheus"
        group: "prometheus"

    - name: Just force systemd to reload configs
      systemd:
        daemon_reload: "yes"

    - name: Start prometheus service
      service:
        name: "prometheus"
        state: "started"
        enabled: "yes"

    - name: Downloading Node Exporter Installion
      unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v0.15.1/node_exporter-0.15.1.linux-amd64.tar.gz"
        dest: "/tmp"
        remote_src: "yes"

    - name: Copy file node_exporter with owner and permissions to bin folder
      copy:
        src: "/tmp/node_exporter-0.15.1.linux-amd64/node_exporter"
        dest: "/usr/local/bin/"
        owner: "node_exporter"
        group: "node_exporter"
        remote_src: "yes"
        mode: "0755"

    - name: Delete node exporter tar.gz folder from tmp folder
      file:
        path: "/tmp/node_exporter-0.15.1.linux-amd64.tar.gz"
        state: "absent"
    
    - name: Delete node exporter folder from tmp folder
      file:
        path: "/tmp/node_exporter-0.15.1.linux-amd64"
        state: "absent"

    - name: Copy file Node Exporter service
      copy:
        src: "/root/Prometheus/config/node_exporter.service"
        dest: "/etc/systemd/system/node_exporter.service"
        owner: "node_exporter"
        group: "node_exporter"
        mode: "0755"

    - name: Just force systemd to reload configs
      systemd:
        daemon_reload: "yes"

    - name: Start node_exporter service
      service:
        name: "node_exporter"
        state: "started"
        enabled: "yes"

    - name: Restart prometheus service
      systemd:
        name: "prometheus"
        state: "restarted"
