- hosts: mysqlserver
  become: true
  tasks:
    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes

    - name: Install MySQL DB server
      apt:
        name: mysql-server
        state: latest
