- hosts: webserver
  become: true
  tasks:
    - name: install apache2
      apt: "name=apache2 update_cache=yes state=latest"

    - name: enabled mod_rewrite
      apache2_module: "name=rewrite state=present"
      notify:
        - restart apache2

    - name: apache2 listen on port 8081
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8081" state=present
      notify:
        - restart apache2

    - name: apache2 virtualhost on port 8081
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8081>" state=present
      notify:
        - restart apache2

    - name: Add PHP 7 PPA repository
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: Install PHP CLI
      apt:
        name: php7.1-cli
        state: latest    

  handlers:
    - name: restart apache2
      service: "name=apache2 state=restarted"
